import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import {BiShoppingBag} from 'react-icons/bi/index';

import { trpc } from "../utils/trpc";
import Image from "next/image";
import { useState } from "react";
import Navbar from "../components/Navbar";
import Featured from "../components/Featured";

const Home = ({cart}: {cart: {
    cart: any;
    addToCart: (id: string, name: string, image: string, description: string, price: number) => void;
    removeFromCart: (id: string) => void;
    addOne: (id: string) => void;
}}) => {
  const [showMenu, setShowMenu] = useState<boolean>(true)
    


  const handleShowMenu = () => {
    setShowMenu(!showMenu)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        {/* <nav className="bg-zinc-900">
          <div className=" py-3 w-full">
              <div className="flex items-center justify-between w-full px-10 max-sm:px-4 max-sm:flex-col max-sm:items-start max-sm:justify-center">
                  <div className="flex justify-between w-full">
                      <a className="text-2xl font-bold text-purple-600 hover:text-purple-700" href="#">Silly Socks</a>
                      <button onClick={handleShowMenu} className="bg-transparent border-0 sm:hidden">
                          <Image src={`/images/menu.png`} alt="menu" className="w-10" width={20} height={20} id="show-menu-btn" />
                      </button>
                  </div>
                  
                  {showMenu && <div className="flex max-sm:flex-col max-sm:items-start  items-center justify-center font-semibold gap-5 max-sm:w-full" >
                    <a className="text-purple-500 max-sm:mt-5 hover:text-purple-700 nav-options max-sm:border-b max-sm:border-zinc-600 w-full" href="#">Home</a>
                    <a className="text-purple-500 hover:text-purple-700 nav-options max-sm:border-b max-sm:border-zinc-600 w-full" href="#">Products</a>
                    <a className="text-purple-500 hover:text-purple-700 nav-options max-sm:border-b max-sm:border-zinc-600 w-full" href="#">About</a>
                    <a className="text-purple-500 hover:text-purple-700 nav-options max-sm:border-b max-sm:border-zinc-600 w-full" href="#">Contact</a>
                  </div>}
                      
                
              </div>
          </div>
        </nav> */}
        {/* https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/Blade06_teamsbackground_Holiday1_382x252_2x?resMode=sharp2&op_usm=1.5,0.65,15,0&wid=786&hei=443&qlt=75&fit=constrain */}
        <div className="relative h-96 shadow-sm shadow-purple-700 " >
          <Image className=" opacity-10 absolute top-0 bottom-0  object-cover object-center h-full w-full" src="/images/sock-bg.png" alt="Background Image" width={500} height={500} />
          <div className="absolute top-0 left-0 w-full h-full  flex justify-center items-center">
              <div className="flex flex-col justify-center items-center max-sm:items-start text-purple-100 w-full max-sm:p-5">
                  <h1 className="text-5xl max-sm:text-3xl font-bold mb-4">Welcome to our Store</h1>
                  <p className="text-lg mb-8 font-semibold">Browse our collection of high-quality products.</p>
                  <Link className="bg-yellow-400 flex items-center gap-2 text-black py-3 px-6 rounded-full text-lg hover:bg-purple-900 hover:text-white transition duration-300 ease-in-out"
                  href={'/shop'}>
                    <BiShoppingBag className="text-2xl"/>
                    <p>Shop Now</p>
                  </Link>
              </div>

          </div>
        </div>

        <section className="pt-8">
        <div className=" mx-auto flex items-center flex-wrap pt-4 pb-12 max-sm:pb-3">
            <h1 className="w-full my-2 text-4xl max-sm:text-3xl font-bold leading-tight text-center text-purple-200 mb-10">Featured Products</h1>
            <div className="w-full mb-4">
            <div className="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t"></div>
            </div>

           
            <Featured cart={cart} />
            <div className="w-full py-16 flex justify-center mt-10">
                <Link href={'/shop'} className="bg-purple-800 w-2/5 p-3 rounded-full hover:bg-purple-700 text-white text-center">See More</Link>
            </div>
          </div>
        </section>
        {/* <div className="py-20 bg-zinc-900"></div> */}
        <section className="bg-zinc-900 py-20 w-full  shadow-lg shadow-zinc-100 border-b border-zinc-800">
        <div className="w-full mx-auto px-4 sm:px-6 lg:px-8">
            <div className="md:flex md:flex-wrap md:-mx-4">
                <div className="md:w-1/2 md:px-4">
                    <h2 className="text-3xl font-extrabold text-zinc-100 mb-4">Our Mission</h2>
                    <p className="text-lg text-zinc-100 mb-6">At Silly Socks and More, we believe that life is too short to wear boring socks. Our mission is to bring a little bit of fun and quirkiness to your everyday wardrobe with our wide selection of colorful, wacky, and whimsical socks. We want to put a smile on your face and help you express your unique personality through your feet.</p>
                    <p className="text-lg text-zinc-100 mb-6"> From funky patterns to cute animal designs, we&apos;ve got something for everyone. But we&apos;re not just about silly socks – we also offer a variety of other fun accessories and gifts to brighten up your day. So, come on in and join us on our mission to spread a little bit of joy, one pair of silly socks at a time!</p>
                </div>
                <div className="md:w-1/2 md:px-4 flex justify-center items-center rounded">
                    <Image width={300} height={300} src="/images/socks-img.png" alt="socks" className="w-2/4 max-sm:w-3/4 max-sm:mt-5 rounded shadow-sm shadow-purple-800" />
                </div>
            </div>
        </div>
        </section>
        <div className="py-12 bg-zinc-900"></div>
        
      
    </>
  );
};

export default Home;

